name: civicfix
description: "CivicFix is a powerful platform empowering citizens to report urban issues like potholes and broken streetlights with ease, using AI validation and real-time tracking, while enabling authorities to resolve them efficiently."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  provider: ^6.1.2
  go_router: ^16.2.0
  shared_preferences: ^2.0.0
  image_picker: '>=1.1.2'
  geolocator: 13.0.4
  permission_handler: ^12.0.0
  uuid: ^4.0.0
  intl: 0.20.2
  cached_network_image: ^3.0.0
  flutter_map: ^8.0.0
  latlong2: 0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/dreamflow_icon.jpg
  remove_alpha_ios: true
